import { NextResponse } from 'next/server';

// This Digital Asset Links file is required for TWA (Trusted Web Activity) APKs.
// The SHA256 fingerprint below is generated by Bubblewrap during APK build.
// After building the APK with Bubblewrap, replace the fingerprint with the one
// from your keystore (run: keytool -list -v -keystore android.keystore)
export async function GET() {
  const assetLinks = [
    {
      relation: ['delegate_permission/common.handle_all_urls'],
      target: {
        namespace: 'android_app',
        package_name: 'com.hotelkarim.admin',
        sha256_cert_fingerprints: [
          // This fingerprint is set during Bubblewrap build.
          // Replace with your actual keystore SHA-256 after building.
          'AA:BB:CC:DD:EE:FF:00:11:22:33:44:55:66:77:88:99:AA:BB:CC:DD:EE:FF:00:11:22:33:44:55:66:77:88:99'
        ],
      },
    },
  ];

  return NextResponse.json(assetLinks, {
    headers: {
      'Content-Type': 'application/json',
      'Cache-Control': 'public, max-age=3600',
    },
  });
}
